[build]
  publish = "out"
[context.production.environment]
  NEXT_SERVERLESS = "true"
  NODE_ENV = "production"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions/"